name: Build and test

on:
  workflow_call:
    inputs:
      openfoam-version:
        type: string
        required: true
      app-version:
        type: string
        default: ${{ github.ref_name }}
        required: false
      source-tarball-url:
        type: string
        default: ''
        required: false
      cache:
        type: boolean
        default: true
        required: false
      release:
        type: boolean
        default: false
        required: false

jobs:
  deps:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache deps
        if: inputs.cache
        uses: actions/cache@v3
        with:
          path: build/*-deps.sparsebundle
          key: deps-${{ inputs.openfoam-version }}-${{ runner.arch }}-${{ hashFiles('Brewfile', 'Makefile') }}
      - name: Reuse cached deps if possible
        run: |
          touch -c build/*-deps.sparsebundle
      - name: Make deps
        run: >
          make deps
          OPENFOAM_VERSION=${{ inputs.openfoam-version }}
      - name: Upload deps artifact
        uses: actions/upload-artifact@v3
        with:
          name: deps-${{ inputs.openfoam-version }}-${{ runner.arch }}
          path: build/*-deps.sparsebundle
          if-no-files-found: error

  build:
    needs: deps
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download deps artifact
        uses: actions/download-artifact@v3
        with:
          name: deps-${{ inputs.openfoam-version }}-${{ runner.arch }}
          path: build
      - name: Use deps artifact
        run: |
          touch -c build/*-deps.sparsebundle
      - name: Cache build
        if: inputs.cache
        uses: actions/cache@v3
        with:
          path: build/*-build.sparsebundle
          key: build-${{ inputs.openfoam-version }}-${{ runner.arch }}-${{ hashFiles('build/*-deps.sparsebundle', 'configure.sh', 'Makefile', format('OpenFOAM-v${0}.tgz.sha256', inputs.openfoam-version)) }}
      - name: Reuse cached build if possible
        run: |
          touch -c build/*-build.sparsebundle
      - name: Build
        run: >
          make build
          OPENFOAM_VERSION=${{ inputs.openfoam-version }}
          ${{ inputs.source-tarball-url != '' && format('SOURCE_TARBALL_URL={0}', inputs.source-tarball-url) || '' }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ inputs.openfoam-version }}-${{ runner.arch }}
          path: build/*-build.sparsebundle
          if-no-files-found: error

  app:
    needs: build
    strategy:
      matrix:
        dependencies-kind: [standalone, homebrew]
      fail-fast: false
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-${{ inputs.openfoam-version }}-${{ runner.arch }}
          path: build
      - name: Use build artifact
        run: |
          touch -c build/*-build.sparsebundle
      - name: Build zipped app
        run: >
          make zip
          APP_VERSION=${{ inputs.app-version }}
          DEPENDENCIES_KIND=${{ matrix.dependencies-kind }}
          OPENFOAM_VERSION=${{ inputs.openfoam-version }}
          ${{ inputs.source-tarball-url != '' && format('SOURCE_TARBALL_URL={0}', inputs.source-tarball-url) || '' }}
      - name: Upload zip artifact
        uses: actions/upload-artifact@v3
        with:
          name: zip-${{ inputs.openfoam-version }}-${{ matrix.dependencies-kind }}-${{ runner.arch }}
          path: build/*-app-*.zip
          if-no-files-found: error

  test:
    needs: app
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12]
        dependencies-kind: [standalone, homebrew]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download ZIP artifact
        uses: actions/download-artifact@v3
        with:
          name: zip-${{ inputs.openfoam-version }}-${{ matrix.dependencies-kind }}-${{ runner.arch }}
          path: build
      - name: Unzip app
        run: |
          unzip *-app-*.zip
        working-directory: build
      - name: Install Homebrew dependencies
        if: matrix.dependencies-kind == 'homebrew'
        run: |
          brew bundle --verbose
      - name: Test
        run: >
          make test
          APP_VERSION=${{ inputs.app-version }}
          OPENFOAM_VERSION=${{ inputs.openfoam-version }}
          DEPENDENCIES_KIND=${{ matrix.dependencies-kind }}

  release:
    needs: test
    if: inputs.release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependencies-kind: [standalone, homebrew]
      fail-fast: false
    steps:
      - name: Download zip artifact
        uses: actions/download-artifact@v3
        with:
          name: zip-${{ inputs.openfoam-version }}-${{ matrix.dependencies-kind }}-${{ runner.arch }}
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: '*-app-*.zip'
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: false
