name: Build and test

on:
  workflow_call:
    inputs:
      openfoam-version:
        type: string
        required: true
      app-version:
        type: string
        default: ''
        required: false
      app-name:
        type: string
        default: ''
        required: false
      openfoam-git-branch:
        type: string
        default: ''
        required: false
      use-cached:
        type: boolean
        default: true
        required: false
      release:
        type: boolean
        default: false
        required: false

env:
  MAKE_VARS: >
    ${{ inputs.openfoam-version != '' && format('OPENFOAM_VERSION={0}', inputs.openfoam-version) || '' }}
    ${{ inputs.app-version != '' && format('APP_VERSION={0}', inputs.app-version) || '' }}
    ${{ inputs.app-name != '' && format('APP_NAME={0}', inputs.app-name) || '' }}
    ${{ inputs.openfoam-git-branch != '' && format('OPENFOAM_GIT_BRANCH={0}', inputs.openfoam-git-branch) || '' }}

jobs:
  deps:
    runs-on: macos-10.15
    concurrency:
      group: deps-${{ inputs.app-name || inputs.openfoam-version }}-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Make recipes for caching
        run: |
          make deps --dry-run $MAKE_VARS > make_deps.txt
      - name: Cache deps
        id: cache_deps
        uses: actions/cache@v3
        with:
          path: |
            build/*-deps.sparsebundle
          key: deps-${{ inputs.app-name || inputs.openfoam-version }}-${{ hashFiles('make_deps.txt', 'Brewfile') }}-${{ github.run_id }}
          restore-keys: |
            deps-${{ inputs.app-name || inputs.openfoam-version }}-${{ hashFiles('make_deps.txt', 'Brewfile') }}-${{ ! inputs.use-cached && 'ignore' || '' }}
      - name: Make deps
        if: steps.cache_deps.outputs.cache-hit != 'true'
        run: |
          touch -c build/*-deps.sparsebundle
          make deps $MAKE_VARS
      - name: Upload deps artifact
        uses: actions/upload-artifact@v3
        with:
          name: deps-${{ inputs.openfoam-version }}
          path: build/*-deps.sparsebundle
          if-no-files-found: error
  
  build:
    needs: deps
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download deps artifact
        uses: actions/download-artifact@v3
        with:
          name: deps-${{ inputs.openfoam-version }}
          path: build
      - name: Get Make recipes for caching
        run: |
          touch -c build/*-deps.sparsebundle
          make build --dry-run $MAKE_VARS > make_build.txt
      - name: Cache build
        id: cache_build
        uses: actions/cache@v3
        with:
          path: |
            build/*-build.sparsebundle
          key: build-${{ inputs.openfoam-version }}-${{ hashFiles('make_build.txt', 'build/*-deps.sparsebundle', format('OpenFOAM-v${0}.tgz.sha256', inputs.openfoam-version), 'configure.sh') }}-${{ github.run_id }}
          restore-keys: |
            build-${{ inputs.openfoam-version }}-${{ hashFiles('make_build.txt', 'build/*-deps.sparsebundle', format('OpenFOAM-v${0}.tgz.sha256', inputs.openfoam-version), 'configure.sh') }}-${{ ! inputs.use-cached && 'ignore' || '' }}
      - name: Build
        if: steps.cache_build.outputs.cache-hit != 'true'
        run: |
          touch -c build/*-build.sparsebundle
          make build $MAKE_VARS
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ inputs.openfoam-version }}
          path: build/*-build.sparsebundle
          if-no-files-found: error

  app:
    needs: build
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-${{ inputs.openfoam-version }}
          path: build
      - name: Make app
        run: |
          touch -c build/*-build.sparsebundle
          make zip $MAKE_VARS
      - name: Upload app artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ inputs.openfoam-version }}
          path: build/*-app-*.zip
          if-no-files-found: error

  test:
    needs: app
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download app artifact
        uses: actions/download-artifact@v3
        with:
          name: app-${{ inputs.openfoam-version }}
          path: build
      - name: Unzip app
        run: |
          unzip *-app-*.zip
        working-directory: build
      - name: Test
        run: |
          make test $MAKE_VARS

  release:
    needs: test
    if: inputs.release
    runs-on: ubuntu-latest
    steps:
      - name: Download app artifact
        uses: actions/download-artifact@v3
        with:
          name: app-${{ inputs.openfoam-version }}
      - name: Upload app to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: '*-app-*.zip'
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: false
