name: Build and test

on:
  workflow_call:
    inputs:
      build-os:
        type: string
        required: true
      openfoam-version:
        type: string
        default: ''
        required: false
      app-version:
        type: string
        default: ''
        required: false
      app-name:
        type: string
        default: ''
        required: false
      openfoam-git-branch:
        type: string
        default: ''
        required: false
      deps-kind:
        type: string
        default: ''
        required: false
      cache-build:
        type: boolean
        default: true
        required: false
  workflow_dispatch:
    inputs:
      build-os:
        type: choice
        required: true
        description: Build using this macOS image
        options:
          - macos-14
          - macos-13
          - macos-12
          - macos-11
      openfoam-version:
        type: string
        default: ''
        required: false
        description: Build this OpenFOAM version
      app-name:
        type: string
        default: ''
        required: false
        description: Override app name
      openfoam-git-branch:
        type: string
        default: ''
        required: false
        description: Build this OpenFOAM Git branch
      deps-kind:
        type: choice
        required: false
        description: Bundle dependencies in this manner
        options:
          - ''
          - standalone
          - bundled
          - homebrew
      cache-build:
        type: boolean
        default: true
        required: false
        description: Cache build artifacts for later reuse

env:
  MAKE_VARS: >
    ${{ inputs.openfoam-version != '' && format('OPENFOAM_VERSION={0}', inputs.openfoam-version) || '' }}
    ${{ inputs.app-version != '' && format('APP_VERSION={0}', inputs.app-version) || '' }}
    ${{ inputs.app-name != '' && format('APP_NAME={0}', inputs.app-name) || '' }}
    ${{ inputs.openfoam-git-branch != '' && format('OPENFOAM_GIT_BRANCH={0}', inputs.openfoam-git-branch) || '' }}
    ${{ inputs.deps-kind != '' && format('DEPS_KIND={0}', inputs.deps-kind) || '' }}

  OPENFOAM: ${{ inputs.openfoam-version || inputs.openfoam-git-branch }}

jobs:
  deps:
    runs-on: ${{ inputs.build-os }}
    outputs:
      deps-key: ${{ steps.keys.outputs.deps-key }}
      build-key: ${{ steps.keys.outputs.build-key }}
    steps:
      - name: Use Xcode Command Line Tools
        run: sudo xcode-select --switch /Library/Developer/CommandLineTools
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare caching
        run: |
          make deps --dry-run ${{ env.MAKE_VARS }} > make_deps.txt
          make build --dry-run ${{ env.MAKE_VARS }} > make_build.txt
          brew update
          brew bundle list | xargs -I {} sh -c 'brew info {} | head -n 1' > brew_versions.txt
          brew deps --union $(brew bundle list) | xargs -I {} sh -c 'brew info {} | head -n 1' >> brew_versions.txt
          sort -u -o brew_versions.txt brew_versions.txt
          cat brew_versions.txt
      - name: Generate caching keys
        id: keys
        run: |
          DEPS_KEY="build-${{ env.OPENFOAM }}-${{ inputs.build-os }}-${{ hashFiles('make_deps.txt', 'Brewfile', 'scripts/bundle_deps.py', 'brew_versions.txt') }}"
          BUILD_KEY="$DEPS_KEY-${{ hashFiles('make_build.txt', 'scripts/configure.sh', 'scripts/relativize_install_names.py') }}"
          echo "deps-key=$DEPS_KEY" >> "$GITHUB_OUTPUT"
          echo "build-key=$BUILD_KEY" >> "$GITHUB_OUTPUT"
      - name: Look up cached deps
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: build/*.sparsebundle
          key: ${{ steps.keys.outputs.build-key }}
          restore-keys: ${{ steps.keys.outputs.deps-key }}
          lookup-only: true
      - name: Make deps
        if: steps.cache.outputs.cache-matched-key == ''
        run: |
          make deps ${{ env.MAKE_VARS }}
      - name: Save deps to cache
        if: steps.cache.outputs.cache-matched-key == ''
        uses: actions/cache/save@v4
        with:
          path: build/*.sparsebundle
          key: ${{ steps.keys.outputs.deps-key }}
  
  build:
    needs: deps
    runs-on: ${{ inputs.build-os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore cached build or deps
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: build/*.sparsebundle
          key: ${{ needs.deps.outputs.build-key }}
          restore-keys: |
            ${{ needs.deps.outputs.deps-key }}
          fail-on-cache-miss: true
      - name: Build
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          hdiutil attach build/*.sparsebundle
          make --touch deps ${{ env.MAKE_VARS }}
          make build ${{ env.MAKE_VARS }}
      - name: Save build to cache
        if: steps.cache.outputs.cache-hit != 'true' && inputs.cache-build
        uses: actions/cache/save@v4
        with:
          path: build/*.sparsebundle
          key: ${{ needs.deps.outputs.build-key }}
      - name: Make app
        run: |
          hdiutil attach build/*.sparsebundle
          make --touch build ${{ env.MAKE_VARS }}
          make zip ${{ env.MAKE_VARS }}
      - name: Upload app artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ env.OPENFOAM }}-${{ runner.arch }}
          path: build/*-app-*.zip
          if-no-files-found: error

  test:
    needs: build
    strategy:
      matrix:
        os: [macos-12, macos-13, macos-14, macos-15]
        exclude:
          - os: ${{ inputs.build-os == 'macos-14' && 'macos-12' || ''}}
          - os: ${{ inputs.build-os == 'macos-14' && 'macos-13' || ''}}
          - os: ${{ inputs.build-os != 'macos-14' && 'macos-14' || ''}}
          - os: ${{ inputs.build-os != 'macos-14' && 'macos-15' || ''}}
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: pip
      - name: Install Homebrew dependencies
        if: inputs.deps-kind == 'homebrew'
        run: |
          brew bundle
      - name: Download app artifact
        uses: actions/download-artifact@v4
        with:
          name: app-${{ env.OPENFOAM }}-${{ runner.arch }}
          path: build
      - name: Unzip app
        run: |
          unzip *-app-*.zip
        working-directory: build
      - name: Test
        run: |
          make test ${{ env.MAKE_VARS }}
        env:
          PRTE_MCA_rmaps_default_mapping_policy: ':oversubscribe'
