name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  openfoam2206:
    name: OpenFOAM-v2206.app
    uses: ./.github/workflows/build-test.yml
    with:
      openfoam-version: 2206
      release: false

  openfoam2112:
    name: OpenFOAM-v2112.app
    uses: ./.github/workflows/build-test.yml
    with:
      openfoam-version: 2112
      release: false
