name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 6 * * 5'
  workflow_dispatch:
    inputs:
      use-cached:
        type: boolean
        default: false
        required: false
        description: Reuse cached build artifacts if available

jobs:
  ci:
    strategy:
      matrix:
        openfoam-version: [2212, 2206, 2112]
      fail-fast: false
    uses: ./.github/workflows/build-test.yml
    with:
      openfoam-version: ${{ matrix.openfoam-version }}
      use-cached: ${{ github.event_name  == 'workflow_dispatch' && inputs.use-cached || github.event_name  != 'workflow_dispatch' && github.event_name != 'schedule' }}
