name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 6 * * 5'
  workflow_dispatch:
    inputs:
      use-cached:
        type: boolean
        default: false
        required: false
        description: Reuse cached build artifacts if available
      build-os:
        type: string
        default: ''
        required: false
        description: macOS version to build on
      cache-build:
        type: boolean
        default: true
        required: false
        description: Cache build artifacts for reuse

jobs:
  ci:
    strategy:
      matrix:
        openfoam-version: [2212, 2206, 2112]
        include:
          - openfoam-version: 2212
            openfoam-tarball-url: https://dl.openfoam.com/source/v2212/OpenFOAM-v2212_230612.tgz
          - openfoam-version: 2112
            openfoam-tarball-url: https://dl.openfoam.com/source/v2112/OpenFOAM-v2112_220610.tgz
      fail-fast: false
    uses: ./.github/workflows/build-test.yml
    with:
      openfoam-version: ${{ matrix.openfoam-version }}
      openfoam-tarball-url: ${{ matrix.openfoam-tarball-url }}
      build-os: ${{ inputs.build-os }}
      use-cached: ${{ github.event_name == 'workflow_dispatch' && inputs.use-cached || github.event_name != 'workflow_dispatch' && github.event_name != 'schedule' }}
      cache-build: ${{ github.event_name != 'workflow_dispatch' && inputs.cache-build || github.event_name != 'workflow_dispatch' }}
