name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 6 * * 5'
  workflow_call:
    inputs:
      app-version:
        type: string
        default: ''
        required: false
      release:
        type: boolean
        default: false
        required: false
  workflow_dispatch:
    inputs:
      use-cached:
        type: boolean
        default: false
        required: false
        description: Reuse cached build artifacts if available
      deps-kind:
          type: choice
          required: false
          description: Bundle dependencies in this manner
          options:
            - ''
            - standalone
            - bundled
            - homebrew
      cache-build:
        type: boolean
        default: true
        required: false
        description: Cache build artifacts for later reuse

jobs:
  ci:
    strategy:
      matrix:
        build-os: [macos-14, macos-12]
        openfoam-version: [2312, 2306]
      fail-fast: false
    uses: ./.github/workflows/build-test.yml
    with:
      openfoam-version: ${{ matrix.openfoam-version }}
      build-os: ${{ matrix.build-os }}
      deps-kind: ${{ inputs.deps-kind }}
      app-version: ${{ github.event_name == 'workflow_call' && inputs.app-version || '' }}
      release: ${{ github.event_name == 'workflow_call' && inputs.release }}
      use-cached: ${{ github.event_name == 'workflow_dispatch' && inputs.use-cached || github.event_name != 'workflow_dispatch' && github.event_name != 'schedule' }}
      cache-build: ${{ github.event_name != 'workflow_dispatch' && inputs.cache-build || github.event_name != 'workflow_dispatch' }}
