name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 6 * * 5'

jobs:
  openfoam2206:
    name: OpenFOAM-v2206.app
    uses: ./.github/workflows/build-test.yml
    with:
      openfoam-version: 2206
      cache: ${{ github.event_name != 'schedule' }}

  openfoam2112:
    name: OpenFOAM-v2112.app
    uses: ./.github/workflows/build-test.yml
    with:
      openfoam-version: 2112
      cache: ${{ github.event_name != 'schedule' }}
