name: OpenFOAM development branches

on:
  schedule:
    - cron: '0 6 * * 5'

jobs:
  openfoam-dev-branch:
    strategy:
      matrix:
        openfoam-git-branch: [master, develop]
      fail-fast: false
    uses: ./.github/workflows/build-test.yml
    with:
      app-name: OpenFOAM-${{ matrix.openfoam-git-branch }}
      app-version: ${{ matrix.openfoam-git-branch }}
      openfoam-git-branch: ${{ matrix.openfoam-git-branch }}
      use-cached: false
      cache-build: false
