name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.get_version.outputs.version-without-v }}
    steps:
      - name: Extract version from release tag
        id: get_version
        uses: battila7/get-version-action@v2

  release:
    needs: get-version
    strategy:
      matrix:
        openfoam-version: [2212, 2206, 2112]
        include:
          - openfoam-version: 2112
            openfoam-tarball-url: https://dl.openfoam.com/source/v2112/OpenFOAM-v2112_220610.tgz
      fail-fast: false
    uses: ./.github/workflows/build-test.yml
    with:
      openfoam-version: ${{ matrix.openfoam-version }}
      openfoam-tarball-url: ${{ matrix.openfoam-tarball-url }}
      app-version: ${{ needs.get-version.outputs.app-version }}
      release: true
