name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.get_version.outputs.VERSION_WITHOUT_V }}
    steps:
      - name: Extract version from tag
        id: get_version
        run:
          echo "VERSION_WITHOUT_V=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"

  build:
    needs: get-version
    uses: ./.github/workflows/ci.yml
    with:
      app-version: ${{ needs.get-version.outputs.app-version }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download app artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: app-*
          merge-multiple: true
      - name: Upload apps to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: '*-app-*.zip'
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: false
