name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.get_version.outputs.VERSION_WITHOUT_V }}
    steps:
      - name: Extract version from tag
        id: get_version
        run:
          echo "VERSION_WITHOUT_V=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"

  release:
    needs: get-version
    strategy:
      matrix:
        openfoam-version: [2306, 2212, 2206, 2112]
      fail-fast: false
    uses: ./.github/workflows/build-test.yml
    with:
      openfoam-version: ${{ matrix.openfoam-version }}
      app-version: ${{ needs.get-version.outputs.app-version }}
      release: true
