name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.get_version.outputs.VERSION_WITHOUT_V }}
    steps:
      - name: Extract version from tag
        id: get_version
        run:
          echo "VERSION_WITHOUT_V=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"

  build:
    needs: get-version
    strategy:
      matrix:
        build-os: [macos-14, macos-12]
        openfoam-version: [2312, 2306]
      fail-fast: false
    uses: ./.github/workflows/build-test.yml
    with:
      openfoam-version: ${{ matrix.openfoam-version }}
      build-os: ${{ matrix.build-os }}
      app-version: ${{ needs.get-version.outputs.app-version }}

  release:
    needs: build
    strategy:
      matrix:
        arch: [ARM64, X64]
        openfoam-version: [2312, 2306]
    runs-on: ubuntu-latest
    steps:
      - name: Download app artifact
        uses: actions/download-artifact@v4
        with:
          name: app-${{ matrix.openfoam-version }}-${{ matrix.arch }}
      - name: Upload app to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: '*-app-*.zip'
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: false
