name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Get version number
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download DMG artifact from previous CI run
        id: download
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          workflow_conclusion: success
          commit: ${{ github.sha }}
          name: dmg
          path: build
        continue-on-error: true
      - name: Set up for partial rebuild
        if: steps.download.outcome == 'success'
        run: |
          make install-dependencies
          make --touch dmg
      - name: Build with version number
        run: |
          make zip APP_VERSION=$APP_VERSION
        env:
          APP_VERSION: ${{ steps.get_version.outputs.version-without-v }}
      - name: Upload DMG artifact
        uses: actions/upload-artifact@v3
        with:
          name: dmg
          path: |
            build/*.dmg
            !build/*-build.dmg
          if-no-files-found: error
      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v3
        with:
          name: zip
          path: build/*.zip
          if-no-files-found: error

  test:
    needs: build
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download DMG artifact
        uses: actions/download-artifact@v3
        with:
          name: dmg
          path: build
      - name: Download ZIP artifact
        uses: actions/download-artifact@v3
        with:
          name: zip
          path: build
      - name: Unzip the app
        run: |
          unzip *.zip
        working-directory: build
      - name: Test
        run: |
          make install-dependencies
          make test

  upload:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download ZIP artifact
        uses: actions/download-artifact@v3
        with:
          name: zip
      - name: Upload ZIP to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: '*.zip'
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: true
