name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version-without-v }}
    steps:
      - name: Get version number
        id: get_version
        uses: battila7/get-version-action@v2

  openfoam2206:
    needs: get-version
    name: OpenFOAM-v2206.app
    uses: ./.github/workflows/build-test.yml
    with:
      openfoam-version: 2206
      app-version: ${{ needs.get-version.outputs.version }}
      release: true

  openfoam2112:
    needs: get-version
    name: OpenFOAM-v2112.app
    uses: ./.github/workflows/build-test.yml
    with:
      openfoam-version: 2112
      app-version: ${{ needs.get-version.outputs.version }}
      release: true
