name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.get_version.outputs.VERSION_WITHOUT_V }}
    steps:
      - name: Extract version from tag
        id: get_version
        run:
          echo "VERSION_WITHOUT_V=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"

  release:
    needs: get-version
    strategy:
      matrix:
        openfoam-version: [2306, 2212, 2206, 2112]
        include:
          - openfoam-version: 2306
            openfoam-tarball-url: https://dl.openfoam.com/source/latest/OpenFOAM-v2306.tgz
          - openfoam-version: 2212
            openfoam-tarball-url: https://dl.openfoam.com/source/v2212/OpenFOAM-v2212_230612.tgz
          - openfoam-version: 2112
            openfoam-tarball-url: https://dl.openfoam.com/source/v2112/OpenFOAM-v2112_220610.tgz
      fail-fast: false
    uses: ./.github/workflows/build-test.yml
    with:
      openfoam-version: ${{ matrix.openfoam-version }}
      openfoam-tarball-url: ${{ matrix.openfoam-tarball-url }}
      openfoam-git-branch: ${{ matrix.openfoam-git-branch }}
      app-version: ${{ needs.get-version.outputs.app-version }}
      release: true
